sudo: required
services:
  - docker

before_install:
  - docker build -t gregbarbosa103/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gregbarbosa103/react-test npm test -- --coverage

after_success:
  - docker build -t gregbarbosa103/multi-client ./client
  - docker build -t gregbarbosa103/multi-nginx ./nginx
  - docker build -t gregbarbosa103/multi-server ./server
  - docker build -t gregbarbosa103/multi-worker ./worker

  # Log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to dockerhub

  - docker push gregbarbosa103/multi-client
  - docker push gregbarbosa103/multi-nginx
  - docker push gregbarbosa103/multi-server
  - docker push gregbarbosa103/multi-worker
